[package]
name = "file_scanner"
version = "0.1.0"
authors = ["Luke Prince <luke@theprinces.org>"]

[dependencies]
clap = "2.32.0"
config = "0.9.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
twox-hash = "1.1.1"
walkdir = "2.2.5"